/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "roman_calc_test_case.tst" instead.
 */

#include <check.h>

#line 1 "roman_calc_test_case.tst"
#include "../roman_conversion/roman_conversion.h"
#include <stdlib.h>

START_TEST(full_roman_calc_test)
{
#line 4
	char *calc_out;
	// Normal add operation
	calc_out = roman_operation("MMD","MMC",'+');
	ck_assert_str_eq(calc_out, "MMMMDC");
	free(calc_out);
	// Sub operation (1st operand greater than 2nd operand)
	calc_out = roman_operation("MMD","MMC",'-');
	ck_assert_str_eq(calc_out, "CD");
	free(calc_out);
	// Sub operation (2nd operand greater than 1st operand)
	// Performs difference operation (2nd operand - 1st operand)
	calc_out = roman_operation("MMC","MMD",'-');
	ck_assert_str_eq(calc_out, "CD");
	free(calc_out);
	// Spaces & tabs introduced before and after valid roman numeral operands
	// Calculator ignores white space and tabs and perform addition
	calc_out = roman_operation("  	MD 	  ","	  	MMCMXCIX	 	  ",'+');
	ck_assert_str_eq(calc_out, "MMMMCDXCIX");
	free(calc_out);
	// Arithmetic output greater than 5000 (Calculator supports roman conversion upto 5000)
	// Calc can accept operands greater than 5000 but the arithmetic result should not
	// be greater than 5000
	calc_out = roman_operation("  	MMD","MMM",'+');
	ck_assert_str_eq(calc_out, "Conversion greater than 5000 not supported");
	free(calc_out);
	calc_out = roman_operation("  	MMMD","MMMMMM",'-');
	ck_assert_str_eq(calc_out, "MMD");
	free(calc_out);
	// Invalid Roman Numerals - Operand1
	calc_out = roman_operation("  	MMD  M","MMC",'+');
	ck_assert_str_eq(calc_out, "Invalid Operand 1 Roman Numerals");
	free(calc_out);
	// Only white space and tabs - Operand1
	calc_out = roman_operation("  	","MMC",'+');
	ck_assert_str_eq(calc_out, "Operand1: Enter Roman Arithmetic Expression");
	free(calc_out);
	// Invalid Roman Numerals - Operand2
	calc_out = roman_operation("  	MMD  ","   	MMC			AA",'+');
	ck_assert_str_eq(calc_out, "Invalid Operand 2 Roman Numerals");
	free(calc_out);
	// Only white space and tabs - Operand2
	calc_out = roman_operation("MMD","			 ",'+');
	ck_assert_str_eq(calc_out, "Operand2: Enter Roman Arithmetic Expression");
	free(calc_out);
	// No arithmetic operator
	calc_out = roman_operation("MMD","  MMC ",' ');
	ck_assert_str_eq(calc_out, "Invalid arithmetic operator");
	free(calc_out);
	// Invalid arithmetic operator
	calc_out = roman_operation("MMD","  MMC ",'*');
	ck_assert_str_eq(calc_out, "Invalid arithmetic operator");
	free(calc_out);
	// Sub operation results in ZERO
	calc_out = roman_operation("MMMMCMXCIX","  MMMMCMXCIX ",'-');
	ck_assert_str_eq(calc_out, "Arithmetic operation result = ZERO");
	free(calc_out);
	// Sub operation  (4999 - 4998 = 1)
	calc_out = roman_operation("MMMMCMXCIX","  MMMMCMXCVIII ",'-');
	ck_assert_str_eq(calc_out, "I");
	free(calc_out);
	// Add operation (1 + 4998 = 4999)
	calc_out = roman_operation("I","  MMMMCMXCVIII ",'+');
	ck_assert_str_eq(calc_out, "MMMMCMXCIX");
	free(calc_out);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, full_roman_calc_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
